### Login
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "test@naver.com",
  "password": "4416"
}

### Create account
POST http://localhost:8080/account
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJPOCs1ZVE1UFdTZ1FQb0JpVHdOenBRPT0iLCJqdGkiOiI3K3dXQnczZmFwd2xZcDV3YXZnTTd3PT0iLCJpYXQiOjE2ODkxMzYwNjQsImV4cCI6MTY4OTEzNzg2NH0.LvT3YCOjPlYH2daZrIYhaQrEPuITjDZx7DuO7d8vzWc

{
  "accountPassword": "0000",
  "bank":  "KB",
  "initialBalance": 500000,
  "setLimit": 50000000,
  "accountType": "INSTALLMENT_SAVING"
}

### Delete account
DELETE http://localhost:8080/account/1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJPOCs1ZVE1UFdTZ1FQb0JpVHdOenBRPT0iLCJqdGkiOiI3K3dXQnczZmFwd2xZcDV3YXZnTTd3PT0iLCJpYXQiOjE2ODg5NzQzNzgsImV4cCI6MTY4ODk3NjE3OH0.PmlRrdBDoyQsL_6MlZ0itZEZXGwOWLmZvYEHiZ5zH70

{
  "accountPassword": "0000",
  "accountNumber": "9320255994",
  "bank":  "KB",
  "accountType": "INSTALLMENT_SAVING"
}

### Search account
GET http://localhost:8080/account?user_id=2
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJPOCs1ZVE1UFdTZ1FQb0JpVHdOenBRPT0iLCJqdGkiOiI3K3dXQnczZmFwd2xZcDV3YXZnTTd3PT0iLCJpYXQiOjE2ODg5NzQzNzgsImV4cCI6MTY4ODk3NjE3OH0.PmlRrdBDoyQsL_6MlZ0itZEZXGwOWLmZvYEHiZ5zH70


### Search account (Bank)
GET http://localhost:8080/account/2/bank?bank=KB
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJPOCs1ZVE1UFdTZ1FQb0JpVHdOenBRPT0iLCJqdGkiOiI3K3dXQnczZmFwd2xZcDV3YXZnTTd3PT0iLCJpYXQiOjE2ODg5NzQzNzgsImV4cCI6MTY4ODk3NjE3OH0.PmlRrdBDoyQsL_6MlZ0itZEZXGwOWLmZvYEHiZ5zH70

### Withdaw money
POST http://localhost:8080/transaction/withdraw
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJPOCs1ZVE1UFdTZ1FQb0JpVHdOenBRPT0iLCJqdGkiOiI3K3dXQnczZmFwd2xZcDV3YXZnTTd3PT0iLCJpYXQiOjE2ODkxMzYwNjQsImV4cCI6MTY4OTEzNzg2NH0.LvT3YCOjPlYH2daZrIYhaQrEPuITjDZx7DuO7d8vzWc

{
  "accountId": 2,
  "accountPassword": "0000",
  "transactionType": "WITHDRAW",
  "amount":  50000
}

### Deposit money
POST http://localhost:8080/transaction/deposit
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJPOCs1ZVE1UFdTZ1FQb0JpVHdOenBRPT0iLCJqdGkiOiI3K3dXQnczZmFwd2xZcDV3YXZnTTd3PT0iLCJpYXQiOjE2ODkxMzYwNjQsImV4cCI6MTY4OTEzNzg2NH0.LvT3YCOjPlYH2daZrIYhaQrEPuITjDZx7DuO7d8vzWc

{
  "accountId": 2,
  "accountPassword": "0000",
  "transactionType": "DEPOSIT",
  "amount":  1000000
}

### remittance money
POST http://localhost:8080/transaction/remittance
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJPOCs1ZVE1UFdTZ1FQb0JpVHdOenBRPT0iLCJqdGkiOiI3K3dXQnczZmFwd2xZcDV3YXZnTTd3PT0iLCJpYXQiOjE2ODkxMzYwNjQsImV4cCI6MTY4OTEzNzg2NH0.LvT3YCOjPlYH2daZrIYhaQrEPuITjDZx7DuO7d8vzWc

{
  "accountId": 1,
  "accountPassword": "0000",
  "bank": "KB",
  "accountNumber": "9691324759",
  "transactionType": "REMITTANCE",
  "amount":  50000
}


### Search transaction
GET http://localhost:8080/transaction/search/1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJPOCs1ZVE1UFdTZ1FQb0JpVHdOenBRPT0iLCJqdGkiOiI3K3dXQnczZmFwd2xZcDV3YXZnTTd3PT0iLCJpYXQiOjE2ODkxMzYwNjQsImV4cCI6MTY4OTEzNzg2NH0.LvT3YCOjPlYH2daZrIYhaQrEPuITjDZx7DuO7d8vzWc
